// Runs in the MAIN world BEFORE wa-js.js, because wa-js reads window.WPPConfig at load
// time and its defaults send data to servers we do not control.
//
// Two channels are off by default in wa-js and must be shut off explicitly:
//
//   disableGoogleAnalytics — wa-js ships the WPPConnect project's own GA4 property
//     (G-MTQ4KY110F) and beacons page views, logins and exceptions to
//     analytics.google.com, keyed to a client id it writes into localStorage on the
//     web.whatsapp.com origin. That is the library author's telemetry, not ours, and our
//     users never agreed to it.
//
//   linkPreview — when an outgoing message contains a URL, wa-js fetches preview data
//     from third-party hosts (uppermesh / titanchat / cloudtrix). That would send our
//     users' outgoing message URLs to strangers, so link previews are generated by
//     WhatsApp itself instead, or not at all.
//
// Keep this file first in the manifest's content_scripts js array.
window.WPPConfig = {
  disableGoogleAnalytics: true,
  sendStatusToDevice: false,
  linkPreviewApiServers: [],
};
